/**
 * Generate 54 skill files across 7 domains.
 * Each skill lives in its own subdirectory with a SKILL.md file.
 * Run: node scripts/generate-skills.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';

const BASE = resolve('data/skills');

const skills = [
  // backend/laravel (15)
  { domain: 'backend/laravel', name: 'eloquent', desc: 'Advanced Eloquent ORM patterns for Laravel including relationship optimization, query scope building, eager loading, chunking large datasets, and database migration best practices', keywords: ['Eloquent ORM', 'relationship optimization', 'eager loading', 'query scopes', 'database migration', 'Laravel model', 'ORM query builder', 'soft deletes', 'accessors', 'mutators'], domains: ['backend', 'database'], whenToUse: 'Use when you need to write efficient database queries in Laravel, build relationships between models, or optimize N+1 query problems. Also apply when creating query scopes, using eager loading, or working with database migrations.', instructions: '1. Analyze the query pattern and identify N+1 risks\n2. Use eager loading with whereHas for filtered relations\n3. Build query scopes for reusable filters\n4. Add indexes for frequently queried columns\n5. Use chunkById for large datasets' },
  { domain: 'backend/laravel', name: 'sanctum', desc: 'Laravel Sanctum authentication for SPA and mobile app APIs, including token management, stateful authentication, CORS configuration, and API route protection', keywords: ['Sanctum', 'API authentication', 'token management', 'SPA auth', 'stateful auth', 'CORS', 'API routes'], domains: ['backend', 'security'], whenToUse: 'Use when implementing API authentication for SPAs or mobile apps, setting up token-based auth, configuring CORS for cross-origin requests, or protecting API routes with Sanctum guards.', instructions: '1. Install and configure Sanctum in config/auth.php\n2. Set up stateful middleware for SPA sessions\n3. Create API tokens with assignToken method\n4. Configure CORS in cors.php for your domains\n5. Protect routes with auth:sanctum middleware' },
  { domain: 'backend/laravel', name: 'queues', desc: 'Laravel queue workers, job dispatching, retry logic, rate limiting, and supervisor configuration for background task processing at scale', keywords: ['queue worker', 'job dispatching', 'retry logic', 'rate limiting', 'supervisor', 'background jobs', 'queued jobs'], domains: ['backend'], whenToUse: 'Use when you need to process heavy tasks asynchronously, send emails in background, handle webhooks, or schedule periodic jobs. Essential for keeping HTTP responses fast.', instructions: '1. Create a Job class with handle() method\n2. Dispatch jobs with dispatch() or dispatchSync()\n3. Configure retry limits and timeout in job class\n4. Set up database or Redis queue driver\n5. Run queue worker with php artisan queue:work' },
  { domain: 'backend/laravel', name: 'pagination', desc: 'Laravel pagination patterns including cursor pagination, simple pagination, lazy loading with cursor, and custom pagination UI components', keywords: ['pagination', 'cursor pagination', 'simple pagination', 'lazy loading', 'paginated responses', 'API pagination'], domains: ['backend'], whenToUse: 'Use when displaying large datasets in tables or lists, building paginated APIs, or optimizing performance for pages with many records.', instructions: '1. Use simplePaginate() for basic two-page navigation\n2. Use paginate() with custom per-page counts\n3. Use cursorPaginate() for large datasets\n4. Return paginated responses with meta data\n5. Implement infinite scroll with cursor tokens' },
  { domain: 'backend/laravel', name: 'validation', desc: 'Laravel Form Request validation, custom validation rules, response formatting for validation errors, and nested array validation patterns', keywords: ['Form Request', 'validation rules', 'custom validator', 'nested validation', 'error formatting'], domains: ['backend'], whenToUse: 'Use when validating incoming request data, creating reusable validation rules, or formatting validation error responses for API consumers.', instructions: '1. Create Form Request classes for complex validation\n2. Define custom Rule objects for reusable rules\n3. Use Rule::in() for enum-style validation\n4. Format errors consistently in API responses\n5. Add custom error messages for better UX' },
  { domain: 'backend/laravel', name: 'migrations', desc: 'Laravel database migrations for schema management, blueprint methods, seeders, rolling back changes, and handling production migrations safely', keywords: ['migrations', 'blueprint', 'schema management', 'seeders', 'rolling back', 'production migrations'], domains: ['backend', 'database'], whenToUse: 'Use when creating or modifying database tables, managing schema changes across environments, seeding test data, or safely deploying schema updates to production.', instructions: '1. Use make:migration with --create flag\n2. Define columns with appropriate types\n3. Add indexes and foreign keys in migration\n4. Create corresponding Seeder classes\n5. Test rollback before deploying to production' },
  { domain: 'backend/laravel', name: 'seeding', desc: 'Laravel database seeding with Factories, Faker integration, relationship seeding, and creating realistic test data for development and testing', keywords: ['seeders', 'Factories', 'Faker', 'test data', 'relationship seeding'], domains: ['backend', 'testing'], whenToUse: 'Use when populating your database with realistic test data, setting up development environment with sample data, or creating deterministic test fixtures.', instructions: '1. Create Factory classes for each model\n2. Use Faker methods to generate realistic data\n3. Seed related models together\n4. Use refreshDatabase trait in tests\n5. Create DatabaseSeeder to orchestrate all seeders' },
  { domain: 'backend/laravel', name: 'factories', desc: 'Laravel model factories for test data generation, state definitions, sequence generation, and factory recycling patterns', keywords: ['factories', 'test data', 'Faker', 'states', 'sequences', 'model factories'], domains: ['backend', 'testing'], whenToUse: 'Use when writing tests that need database records, generating realistic test data, or creating parameterized test scenarios with different model states.', instructions: '1. Define factory states for different model variants\n2. Use sequence() for sequential values\n3. Chain states with afterMaking() and afterCreating()\n4. Use Recycler for unique values\n5. Test factories with php artisan tinker' },
  { domain: 'backend/laravel', name: 'api-resources', desc: 'Laravel API Resources for transforming model data into JSON responses, conditional field inclusion, resource collections, and nested resource responses', keywords: ['API Resources', 'JSON transformation', 'resource collections', 'conditional fields', 'API responses'], domains: ['backend', 'api'], whenToUse: 'Use when building REST API endpoints, transforming Eloquent models to JSON, conditionally including fields based on user permissions, or creating nested API responses.', instructions: '1. Create Resource classes extending JsonResource\n2. Define toArray() method for field mapping\n3. Use when() for conditional fields\n4. Create ResourceCollection for multiple resources\n5. Return resources from controller methods' },
  { domain: 'backend/laravel', name: 'events-listeners', desc: 'Laravel event system for decoupled architecture, queued events, event subscribers, and firing custom application events', keywords: ['events', 'listeners', 'queued events', 'event subscribers', 'decoupled architecture'], domains: ['backend'], whenToUse: 'Use when you need to decouple business logic, handle side effects asynchronously, or trigger multiple actions from a single event like user registration.', instructions: '1. Define Event classes with payload data\n2. Create Listener classes with handle() method\n3. Register in EventServiceProvider\n4. Make events queued for background processing\n5. Use Event::fake() in tests' },
  { domain: 'backend/laravel', name: 'middleware', desc: 'Laravel HTTP middleware for request filtering, route middleware groups, middleware piping, and creating custom middleware for authentication and rate limiting', keywords: ['middleware', 'request filtering', 'route middleware', 'middleware groups', 'custom middleware'], domains: ['backend', 'security'], whenToUse: 'Use when you need to filter HTTP requests, add authentication checks, implement rate limiting, or create reusable request processing layers.', instructions: '1. Create middleware with make:middleware\n2. Handle method for request processing\n3. Register in Kernel.php or use anonymous middleware\n4. Group middleware for route groups\n5. Test middleware with Http facade' },
  { domain: 'backend/laravel', name: 'service-container', desc: 'Laravel Service Container and Service Providers for dependency injection, binding interfaces to implementations, and managing application services', keywords: ['Service Container', 'dependency injection', 'Service Provider', 'bindings', 'IOC container'], domains: ['backend'], whenToUse: 'Use when implementing dependency injection, binding interfaces to concrete classes, registering services with the container, or creating custom Service Providers.', instructions: '1. Bind interfaces to implementations in Service Providers\n2. Use type-hinted constructor injection\n3. Resolve services with app() helper\n4. Use bind() for singleton, singleton() for shared instances\n5. Test bindings with container inspection' },
  { domain: 'backend/laravel', name: 'task-scheduling', desc: 'Laravel Task Scheduling for recurring jobs, cron configuration, command scheduling, and monitoring scheduled tasks in production', keywords: ['task scheduling', 'cron', 'scheduled commands', 'schedule work', 'recurring jobs'], domains: ['backend'], whenToUse: 'Use when you need to run periodic background tasks like daily reports, cleanup jobs, or scheduled API calls without managing external cron configurations.', instructions: '1. Define schedules in Kernel.php schedule() method\n2. Use everyHour(), daily(), weekly() convenience methods\n3. Configure cron on server for Laravel scheduler\n4. Add shouldRun() for conditional execution\n5. Monitor with php artisan schedule:work' },
  { domain: 'backend/laravel', name: 'cache', desc: 'Laravel caching strategies including cache tags, cache locking, Redis integration, cache busting, and multi-layer caching patterns', keywords: ['caching', 'cache tags', 'Redis', 'cache locking', 'cache busting'], domains: ['backend'], whenToUse: 'Use when optimizing slow database queries, storing frequently accessed data, implementing distributed locks, or reducing API response times.', instructions: '1. Use Cache::remember() for auto-expiring cache\n2. Implement cache tags for grouped invalidation\n3. Use Cache::lock() for distributed locks\n4. Configure Redis as cache driver in production\n5. Monitor cache hit rates in Telescope' },
  { domain: 'backend/laravel', name: 'http-client', desc: 'Laravel HTTP Client for making outbound API requests, handling responses, request retries, and mocking HTTP calls in tests', keywords: ['HTTP client', 'API requests', 'response handling', 'request retries', 'HTTP mocking'], domains: ['backend', 'api'], whenToUse: 'Use when integrating with external APIs, making HTTP requests from Laravel, handling API response errors, or testing code that makes external HTTP calls.', instructions: '1. Use Http::get() and Http::post() for requests\n2. Handle responses with optional() method\n3. Add retry() for automatic retries on failure\n4. Mock HTTP calls with Http::fake() in tests\n5. Use withHeaders() for authentication tokens' },

  // backend/api (5)
  { domain: 'backend/api', name: 'rest-conventions', desc: 'RESTful API design conventions including proper HTTP methods, status codes, resource naming, HATEOAS links, and API versioning strategies', keywords: ['REST API', 'HTTP methods', 'status codes', 'resource naming', 'HATEOAS', 'API design'], domains: ['backend', 'api'], whenToUse: 'Use when designing new API endpoints, reviewing existing API contracts, or establishing API standards for a team. Essential for building consistent and predictable APIs.', instructions: '1. Use GET for reads, POST for creates, PUT/PATCH for updates, DELETE for removals\n2. Return appropriate status codes: 200, 201, 400, 401, 404, 422, 500\n3. Name resources in plural lowercase with hyphens\n4. Include pagination metadata in list responses\n5. Version APIs via URL path or Accept header' },
  { domain: 'backend/api', name: 'versioning', desc: 'API versioning strategies including URL path versioning, header versioning, content negotiation, and backward compatibility maintenance', keywords: ['API versioning', 'URL versioning', 'content negotiation', 'backward compatibility', 'deprecated endpoints'], domains: ['backend', 'api'], whenToUse: 'Use when introducing breaking API changes, maintaining multiple client versions, or deprecating old API endpoints while supporting existing consumers.', instructions: '1. Use URL path versioning: /api/v1/resources\n2. Maintain backward compatibility when possible\n3. Deprecate endpoints with warning headers\n4. Document version changes in API changelog\n5. Set sunset headers for deprecated versions' },
  { domain: 'backend/api', name: 'errors', desc: 'Consistent API error response formatting, problem details specification, error code taxonomy, and error handling middleware patterns', keywords: ['error handling', 'Problem Details', 'error codes', 'API errors', 'error responses'], domains: ['backend', 'api'], whenToUse: 'Use when designing error response formats, implementing centralized error handling, or standardizing error codes across your API surface.', instructions: '1. Follow RFC 7807 Problem Details format\n2. Include error code, title, detail, and instance\n3. Use standard HTTP status codes consistently\n4. Add validation errors with field-level details\n5. Log errors with correlation IDs for debugging' },
  { domain: 'backend/api', name: 'rate-limiting', desc: 'API rate limiting strategies including token bucket algorithm, sliding window counters, per-user limits, and rate limit response headers', keywords: ['rate limiting', 'token bucket', 'sliding window', 'API throttling', 'rate limit headers'], domains: ['backend', 'security'], whenToUse: 'Use when protecting APIs from abuse, implementing usage quotas, preventing brute force attacks, or managing resource-intensive operations.', instructions: '1. Implement token bucket or sliding window algorithm\n2. Return standard rate limit headers (X-RateLimit-*)\n3. Apply different limits per user tier\n4. Cache rate limit checks for performance\n5. Return 429 with Retry-After header on limit exceeded' },
  { domain: 'backend/api', name: 'graphql-basics', desc: 'GraphQL schema design, resolver patterns, DataLoader for N+1 prevention, introspection, and GraphQL versus REST tradeoffs', keywords: ['GraphQL', 'schema design', 'resolvers', 'DataLoader', 'N+1 queries', 'GraphQL API'], domains: ['backend', 'api'], whenToUse: 'Use when building flexible APIs with complex data requirements, reducing over-fetching, or enabling client-driven queries with typed schemas.', instructions: '1. Define schema with SDL (Schema Definition Language)\n2. Create resolvers for each field\n3. Use DataLoader to batch database queries\n4. Enable introspection in development only\n5. Document schema with descriptions' },

  // frontend/react (10)
  { domain: 'frontend/react', name: 'hooks-basics', desc: 'React Hooks fundamentals including useState, useEffect, useContext, useReducer, custom hooks, and hook rules and best practices', keywords: ['useState', 'useEffect', 'useContext', 'useReducer', 'custom hooks', 'React Hooks'], domains: ['frontend'], whenToUse: 'Use when building React components with state management, side effects, context sharing, or extracting reusable logic into custom hooks.', instructions: '1. useState for component-local state\n2. useEffect for side effects and subscriptions\n3. useContext for cross-component data sharing\n4. useReducer for complex state logic\n5. Extract custom hooks for reusable logic' },
  { domain: 'frontend/react', name: 'patterns', desc: 'React component patterns including Compound Components, Render Props, Higher-Order Components, Control Props, and the Hook Rules', keywords: ['Compound Components', 'Render Props', 'HOC', 'Control Props', 'component patterns'], domains: ['frontend'], whenToUse: 'Use when designing reusable component APIs, choosing between composition patterns, or structuring complex component hierarchies.', instructions: '1. Prefer Compound Components for flexible APIs\n2. Use Render Props for cross-cutting logic\n3. Apply HOCs sparingly for wrapper behavior\n4. Use Control Props for parent-controlled state\n5. Follow Hook Rules: only at top level' },
  { domain: 'frontend/react', name: 'state-management', desc: 'React state management at scale including Zustand, Jotai, Redux Toolkit, context patterns, and state colocation principles', keywords: ['Zustand', 'Jotai', 'Redux Toolkit', 'context', 'state management', 'global state'], domains: ['frontend'], whenToUse: 'Use when managing complex application state, sharing data across many components, or replacing prop drilling with scalable state solutions.', instructions: '1. Keep state as close to usage as possible\n2. Use Zustand for global state without boilerplate\n3. Use Jotai for atomic state management\n4. Reserve Redux for complex state transitions\n5. Avoid context for frequently changing state' },
  { domain: 'frontend/react', name: 'performance', desc: 'React performance optimization including memoization, lazy loading, code splitting, virtualization, and profiling with React DevTools', keywords: ['memoization', 'React.memo', 'lazy loading', 'code splitting', 'virtualization', 'performance'], domains: ['frontend'], whenToUse: 'Use when diagnosing render performance issues, optimizing bundle size, implementing virtualized lists, or reducing unnecessary re-renders.', instructions: '1. Wrap expensive components with React.memo\n2. Use useMemo and useCallback for derived values\n3. Implement React.lazy() for code splitting\n4. Use react-window for long list rendering\n5. Profile with React DevTools Profiler' },
  { domain: 'frontend/react', name: 'testing', desc: 'React component testing with React Testing Library, testing hooks, testing async behavior, mocking APIs, and snapshot testing strategies', keywords: ['React Testing Library', 'RTL', 'hook testing', 'async testing', 'mocking', 'snapshot testing'], domains: ['frontend', 'testing'], whenToUse: 'Use when writing unit tests for React components, testing custom hooks, simulating async behavior, or verifying UI interactions.', instructions: '1. Query by user-facing labels and roles\n2. Test behavior not implementation\n3. Use @testing-library/react-hooks for hook tests\n4. Mock APIs with MSW or jest.fn()\n5. Avoid testing internals and implementation details' },
  { domain: 'frontend/react', name: 'forms', desc: 'React form handling with React Hook Form, Zod validation, controlled vs uncontrolled components, form state management, and submission patterns', keywords: ['React Hook Form', 'Zod', 'form validation', 'controlled components', 'form submission'], domains: ['frontend'], whenToUse: 'Use when building complex forms with validation, handling form state efficiently, or implementing multi-step form wizards.', instructions: '1. Use React Hook Form for performance\n2. Validate with Zod schema\n3. Prefer uncontrolled components where possible\n4. Handle submission with async handlers\n5. Show field-level validation errors' },
  { domain: 'frontend/react', name: 'portals', desc: 'React Portals for rendering children outside parent DOM hierarchy, modal dialogs, tooltips, dropdowns, and overlay components', keywords: ['Portals', 'modal dialogs', 'overlays', 'tooltip', 'z-index', 'DOM rendering'], domains: ['frontend'], whenToUse: 'Use when creating modals, tooltips, dropdowns, or any component that needs to escape parent DOM constraints for z-index or overflow handling.', instructions: '1. Use ReactDOM.createPortal for portal creation\n2. Provide container element reference\n3. Handle focus trapping in portals\n4. Clean up event listeners on unmount\n5. Style portals with position: fixed' },
  { domain: 'frontend/react', name: 'suspense', desc: 'React Suspense for data fetching, lazy component loading, error boundaries, and streaming SSR with concurrent features', keywords: ['Suspense', 'lazy loading', 'error boundaries', 'concurrent features', 'streaming SSR'], domains: ['frontend'], whenToUse: 'Use when implementing lazy-loaded components, suspense-based data fetching, or graceful fallback UI during asynchronous operations.', instructions: '1. Wrap lazy imports with React.lazy()\n2. Provide fallback UI with Suspense boundary\n3. Use ErrorBoundary for error handling\n4. Implement useSuspenseQuery for data fetching\n5. Combine with concurrent mode features' },
  { domain: 'frontend/react', name: 'context', desc: 'React Context API for global state sharing, context providers, context optimization, and avoiding unnecessary re-renders', keywords: ['Context API', 'providers', 'context optimization', 'useContext', 're-render prevention'], domains: ['frontend'], whenToUse: 'Use when sharing theme data, authentication state, or locale settings across deeply nested component trees without prop drilling.', instructions: '1. Create context with createContext()\n2. Wrap app with provider component\n3. Split contexts to prevent unwanted re-renders\n4. Use context selector pattern for performance\n5. Combine with useReducer for complex state' },
  { domain: 'frontend/react', name: 'refs', desc: 'React refs including useRef, useImperativeHandle, forwardRef, DOM ref manipulation, and ref callback patterns', keywords: ['useRef', 'forwardRef', 'useImperativeHandle', 'DOM refs', 'ref callbacks'], domains: ['frontend'], whenToUse: 'Use when accessing DOM elements directly, managing focus, integrating with third-party libraries, or exposing imperative methods from child components.', instructions: '1. Use useRef for mutable values that persist\n2. Use forwardRef when wrapping components\n3. Use useImperativeHandle to expose methods\n4. Access DOM nodes with ref.current\n5. Avoid ref abuse for state management' },

  // frontend/nextjs (8)
  { domain: 'frontend/nextjs', name: 'app-router', desc: 'Next.js App Router with React Server Components, layouts, loading states, error boundaries, and route groups', keywords: ['App Router', 'Server Components', 'layouts', 'loading.tsx', 'error.tsx', 'route groups'], domains: ['frontend'], whenToUse: 'Use when building Next.js 13+ applications with the App Router, creating nested layouts, implementing loading states, or organizing routes with route groups.', instructions: '1. Create page.tsx for each route segment\n2. Use layout.tsx for shared UI\n3. Add loading.tsx for skeleton screens\n4. Handle errors with error.tsx\n5. Use route groups with () parentheses' },
  { domain: 'frontend/nextjs', name: 'server-components', desc: 'React Server Components in Next.js, data fetching patterns, client interaction, and the server-client component boundary', keywords: ['Server Components', 'RSC', 'data fetching', 'client components', 'use client'], domains: ['frontend'], whenToUse: 'Use when fetching data directly in components, reducing client-side JavaScript bundle, or optimizing performance with server-rendered components.', instructions: '1. Components are server by default in App Router\n2. Use "use client" for interactive components\n3. Fetch data directly in server components\n4. Pass data as props to client components\n5. Keep client components minimal' },
  { domain: 'frontend/nextjs', name: 'data-fetching', desc: 'Next.js data fetching strategies including Server Components fetch, useSWR, cache revalidation, and full-route cache control', keywords: ['data fetching', 'useSWR', 'cache revalidation', 'stale-while-revalidate', 'full-route cache'], domains: ['frontend'], whenToUse: 'Use when implementing data fetching in Next.js, choosing between static and dynamic rendering, or managing cache revalidation strategies.', instructions: '1. Fetch in Server Components with async/await\n2. Use unstable_noStore() for dynamic data\n3. Configure cache options on fetch()\n4. Implement revalidatePath for mutations\n5. Use useSWR for client-side caching' },
  { domain: 'frontend/nextjs', name: 'middleware', desc: 'Next.js middleware for request rewriting, authentication checks, A/B testing, and edge runtime optimizations', keywords: ['middleware', 'request rewriting', 'authentication', 'A/B testing', 'edge runtime'], domains: ['frontend', 'security'], whenToUse: 'Use when implementing route protection, A/B testing experiments, request rewriting, or geo-based routing without server-side logic.', instructions: '1. Create middleware.ts in project root\n2. Match routes with matcher config\n3. Use NextResponse.rewrite() for routing\n4. Check authentication tokens in middleware\n5. Deploy to Edge Runtime for performance' },
  { domain: 'frontend/nextjs', name: 'image-optimization', desc: 'Next.js Image component for automatic optimization, responsive images, lazy loading, and custom image domain configuration', keywords: ['Image component', 'image optimization', 'lazy loading', 'responsive images', 'next/image'], domains: ['frontend'], whenToUse: 'Use when displaying images in Next.js applications, optimizing image load times, or serving responsive images across devices.', instructions: '1. Use next/image instead of <img> tag\n2. Set proper width and height attributes\n3. Configure remotePatterns in next.config.js\n4. Use priority prop for above-fold images\n5. Enable blur placeholder for LQIP' },
  { domain: 'frontend/nextjs', name: 'file-routing', desc: 'Next.js file-based routing conventions, dynamic routes with [slug], catch-all routes with [...slug], and route segments', keywords: ['file routing', 'dynamic routes', 'catch-all routes', 'route segments', '[slug]'], domains: ['frontend'], whenToUse: 'Use when defining URL routes by file structure, creating dynamic pages from URL parameters, or implementing catch-all routes for nested content.', instructions: '1. Create page.tsx for each route\n2. Use [id].tsx for dynamic segments\n3. Use [...slug].tsx for catch-all routes\n4. Access params in page component\n5. Organize route groups with ()' },
  { domain: 'frontend/nextjs', name: 'api-routes', desc: 'Next.js API Routes for serverless functions, request handling, CORS configuration, and middleware integration with API endpoints', keywords: ['API Routes', 'serverless functions', 'request handling', 'API handlers', 'server actions'], domains: ['frontend', 'api'], whenToUse: 'Use when creating backend API endpoints in Next.js, handling form submissions server-side, or building serverless functions without external backend.', instructions: '1. Create routes/app/api/endpoint/route.ts\n2. Export GET, POST, PUT, DELETE handlers\n3. Return NextResponse for structured replies\n4. Handle CORS with response headers\n5. Use server actions for mutations' },
  { domain: 'frontend/nextjs', name: 'static-generation', desc: 'Next.js static site generation with generateStaticParams, full static rendering, ISR with revalidate, and partial prerendering', keywords: ['static generation', 'generateStaticParams', 'ISR', 'revalidate', 'partial prerendering'], domains: ['frontend'], whenToUse: 'Use when building statically generated pages, implementing Incremental Static Regeneration, or optimizing pages that rarely change.', instructions: '1. Use generateStaticParams for dynamic routes\n2. Set export const dynamic = \'force-static\'\n3. Configure revalidate for ISR\n4. Use generateMetadata for SEO\n5. Pre-render at build time with next build' },

  // design (6)
  { domain: 'design', name: 'color-theory', desc: 'Color theory fundamentals for web design including color wheels, harmony schemes, accessibility contrast, and semantic color systems', keywords: ['color theory', 'color harmony', 'contrast ratio', 'semantic colors', 'design tokens'], domains: ['design'], whenToUse: 'Use when building color systems, choosing color palettes, ensuring accessibility compliance, or creating consistent design token sets.', instructions: '1. Start with a base hue and build palette\n2. Ensure 4.5:1 contrast for text\n3. Use semantic tokens: primary, secondary, surface\n4. Test with color blindness simulators\n5. Document color usage in design system' },
  { domain: 'design', name: 'typography', desc: 'Web typography systems including font pairing, scale ratios, line height, responsive type scaling, and web font optimization', keywords: ['typography', 'font pairing', 'type scale', 'responsive type', 'web fonts'], domains: ['design'], whenToUse: 'Use when establishing typographic hierarchies, selecting font families, setting responsive type scales, or optimizing web font delivery.', instructions: '1. Choose max 2 font families\n2. Use modular scale for type sizes\n3. Set line-height to 1.5 for body text\n4. Use clamp() for responsive scaling\n5. Subset and preload web fonts' },
  { domain: 'design', name: 'glassmorphism', desc: 'Glassmorphism UI design patterns including backdrop blur effects, frosted glass cards, layered transparency, and modern aesthetic techniques', keywords: ['glassmorphism', 'backdrop blur', 'frosted glass', 'transparency', 'layered UI'], domains: ['design'], whenToUse: 'Use when creating modern glass-like UI elements, implementing backdrop blur effects, or designing translucent card components with depth.', instructions: '1. Use backdrop-filter: blur() for frosted effect\n2. Add semi-transparent white backgrounds\n3. Include subtle borders for depth\n4. Layer multiple glass elements\n5. Ensure text contrast on blurred backgrounds' },
  { domain: 'design', name: 'spacing', desc: 'Design spacing systems using modular scales, padding tokens, gap utilities, and consistent rhythm for UI layouts', keywords: ['spacing system', 'modular scale', 'padding tokens', 'gap utilities', 'visual rhythm'], domains: ['design'], whenToUse: 'Use when creating consistent spacing systems, defining token scales, or establishing visual rhythm across UI components.', instructions: '1. Use 4px or 8px base grid\n2. Create spacing scale: 4, 8, 12, 16, 24, 32, 48\n3. Use CSS custom properties for tokens\n4. Apply consistent gap values\n5. Test spacing at different breakpoints' },
  { domain: 'design', name: 'responsive-design', desc: 'Responsive design patterns including mobile-first approach, breakpoints, fluid grids, container queries, and adaptive images', keywords: ['responsive design', 'mobile-first', 'breakpoints', 'fluid grids', 'container queries'], domains: ['design', 'frontend'], whenToUse: 'Use when building responsive layouts, implementing mobile-first CSS, choosing breakpoint values, or creating adaptive component designs.', instructions: '1. Start with mobile styles first\n2. Use min-width media queries\n3. Set breakpoints at content needs\n4. Use container queries for components\n5. Test on real devices' },
  { domain: 'design', name: 'accessibility', desc: 'Web accessibility including WCAG 2.1 AA compliance, ARIA attributes, keyboard navigation, screen reader testing, and accessible color contrast', keywords: ['accessibility', 'WCAG 2.1', 'ARIA', 'keyboard navigation', 'screen readers', 'contrast'], domains: ['design'], whenToUse: 'Use when ensuring web accessibility compliance, implementing ARIA attributes, testing keyboard navigation, or auditing color contrast ratios.', instructions: '1. Target WCAG 2.1 AA compliance\n2. Use semantic HTML elements\n3. Add ARIA labels where needed\n4. Ensure full keyboard navigation\n5. Test with screen readers' },

  // testing (5)
  { domain: 'testing', name: 'pest-php', desc: 'Pest PHP testing framework for Laravel including feature tests, unit tests, database assertions, and test coverage reporting', keywords: ['Pest PHP', 'feature tests', 'unit tests', 'database assertions', 'Laravel testing'], domains: ['testing', 'backend'], whenToUse: 'Use when writing Laravel tests with Pest PHP, creating feature test suites, asserting database state, or generating test coverage reports.', instructions: '1. Create tests with pest command\n2. Use expect() for expressive assertions\n3. Test HTTP responses with assertStatus()\n4. Assert database state with assertDatabaseHas()\n5. Generate coverage with --coverage flag' },
  { domain: 'testing', name: 'vitest', desc: 'Vitest testing framework for Vite projects including unit tests, component tests, mocking, and integration test patterns', keywords: ['Vitest', 'unit testing', 'component testing', 'mocking', 'Vite testing'], domains: ['testing', 'frontend'], whenToUse: 'Use when testing Vite-based frontend projects, writing unit tests for utilities, testing React components, or mocking API calls in tests.', instructions: '1. Configure vitest.config.ts\n2. Use describe/it/expect pattern\n3. Mock modules with vi.mock()\n4. Run with --coverage for reports\n5. Use testcontainers for integration tests' },
  { domain: 'testing', name: 'playwright', desc: 'Playwright end-to-end testing for web applications including browser automation, visual testing, API testing, and CI integration', keywords: ['Playwright', 'E2E testing', 'browser automation', 'visual testing', 'API testing'], domains: ['testing'], whenToUse: 'Use when writing end-to-end browser tests, automating user interactions, performing visual regression testing, or testing cross-browser compatibility.', instructions: '1. Install Playwright with npx playwright install\n2. Create tests with test.describe()\n3. Interact with pages using selectors\n4. Take screenshots for visual testing\n5. Run in CI with parallel workers' },
  { domain: 'testing', name: 'tdd-basics', desc: 'Test-Driven Development fundamentals including red-green-refactor cycle, test naming conventions, and writing tests before implementation', keywords: ['TDD', 'red-green-refactor', 'test naming', 'test-driven development'], domains: ['testing'], whenToUse: 'Use when following TDD methodology, writing tests before code, establishing test naming conventions, or teaching TDD practices to a team.', instructions: '1. Write failing test first (Red)\n2. Write minimum code to pass (Green)\n3. Refactor with confidence (Refactor)\n4. Use descriptive test names\n5. Keep tests independent and fast' },
  { domain: 'testing', name: 'integration-testing', desc: 'Integration testing patterns including test databases, mocking external services, transaction rollback, and test isolation strategies', keywords: ['integration tests', 'test database', 'mocking', 'transaction rollback', 'test isolation'], domains: ['testing'], whenToUse: 'Use when testing interactions between multiple system components, integrating with external APIs in tests, or managing test database state.', instructions: '1. Use dedicated test database\n2. Wrap tests in transactions\n3. Mock external HTTP calls\n4. Reset state between tests\n5. Use factories for test data' },

  // meta (5)
  { domain: 'meta', name: 'debugging', desc: 'Systematic debugging techniques including console diagnostics, stack trace analysis, breakpoint strategies, memory leak detection, and root cause analysis', keywords: ['debugging', 'stack traces', 'breakpoints', 'memory leaks', 'root cause analysis', 'console diagnostics'], domains: ['debugging', 'diagnostics'], whenToUse: 'Use when investigating bugs, analyzing stack traces, detecting memory leaks, or systematically debugging application issues.', instructions: '1. Reproduce the issue consistently\n2. Check console for errors and warnings\n3. Use breakpoints at suspected failure points\n4. Analyze stack traces top-down\n5. Isolate variables to find root cause' },
  { domain: 'meta', name: 'refactoring', desc: 'Code refactoring techniques including extracting functions, renaming for clarity, simplifying conditions, and maintaining behavior while improving structure', keywords: ['refactoring', 'code cleanup', 'extract function', 'rename', 'simplicity'], domains: ['meta'], whenToUse: 'Use when improving code readability, reducing complexity, eliminating duplication, or preparing code for new features without changing behavior.', instructions: '1. Write tests before refactoring\n2. Make small incremental changes\n3. Extract functions for clarity\n4. Rename variables for intent\n5. Run tests after each change' },
  { domain: 'meta', name: 'code-review', desc: 'Code review best practices including review checklists, constructive feedback, security review patterns, and performance review techniques', keywords: ['code review', 'review checklist', 'constructive feedback', 'security review', 'performance review'], domains: ['meta'], whenToUse: 'Use when reviewing pull requests, establishing code review processes, checking for security issues, or providing constructive feedback.', instructions: '1. Review one concern at a time\n2. Ask questions not commands\n3. Check for security vulnerabilities\n4. Look for performance bottlenecks\n5. Praise good practices too' },
  { domain: 'meta', name: 'architecture', desc: 'Software architecture patterns including MVC, layered architecture, event-driven design, microservices patterns, and architectural decision records', keywords: ['architecture', 'MVC', 'layered architecture', 'event-driven', 'microservices', 'ADR'], domains: ['meta'], whenToUse: 'Use when designing system architecture, choosing architectural patterns, documenting technical decisions, or planning scalable system structure.', instructions: '1. Start with requirements and constraints\n2. Choose patterns that fit the domain\n3. Document decisions with ADRs\n4. Consider trade-offs explicitly\n5. Iterate architecture over time' },
  { domain: 'meta', name: 'documentation', desc: 'Technical documentation practices including README structure, API documentation, architecture diagrams, changelog maintenance, and contributor guides', keywords: ['documentation', 'README', 'API docs', 'diagrams', 'changelog', 'contributing guide'], domains: ['meta'], whenToUse: 'Use when writing project documentation, creating API references, maintaining changelogs, or onboarding new contributors to a codebase.', instructions: '1. Start README with setup instructions\n2. Document public APIs with examples\n3. Use diagrams for complex flows\n4. Keep changelog up to date\n5. Include contributing guidelines' },
];

async function main() {
  for (const skill of skills) {
    const dir = join(BASE, skill.domain, skill.name);
    await mkdir(dir, { recursive: true });
    const content = `---
name: ${skill.name}
description: ${skill.desc}
keywords:
${skill.keywords.map((kw) => `  - ${kw}`).join('\n')}
domains:
${skill.domains.map((d) => `  - ${d}`).join('\n')}
---

## When to use

${skill.whenToUse}

## Instructions

${skill.instructions}
`;
    const filePath = join(dir, 'SKILL.md');
    await writeFile(filePath, content, 'utf-8');
    console.log(`Created ${filePath}`);
  }
  console.log(`\nCreated ${skills.length} skill files.`);
}

main().catch(console.error);
